name: Build & Release Go Binary for Termux (armv7l)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Go binary for armv7l
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Tidy Go modules
        run: go mod tidy

      - name: Build for Linux ARMv7 (Termux compatible)
        env:
          GOOS: linux
          GOARCH: arm
          GOARM: 7
        run: |
          mkdir -p dist
          go build -o dist/MaskLR-Go-${{ github.ref_name }} ./

      - name: Make binary executable
        run: chmod +x dist/MaskLR-Go-${{ github.ref_name }}

      - name: Generate SHA256 checksum
        run: sha256sum dist/MaskLR-Go-${{ github.ref_name }} > dist/MaskLR-Go-${{ github.ref_name }}.sha256

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/MaskLR-Go-${{ github.ref_name }}
            dist/MaskLR-Go-${{ github.ref_name }}.sha256
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
