name: Release MaskLR-Go for Android armv7l

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Download Go dependencies and generate go.sum
      run: go mod tidy

    - name: Build ARMv7 binary with Makefile
      run: make build

    - name: Upload binary to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/masklr-linux-armv7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
