name: Build & Release with Makefile

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Build with Makefile (Termux ARMv7)
        run: make build-armv7 VERSION=${{ github.ref_name }}

      - name: Generate SHA256 checksum
        run: |
          cd dist
          sha256sum MaskLR-Go-armv7-${{ github.ref_name }} > MaskLR-Go-armv7-${{ github.ref_name }}.sha256

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/MaskLR-Go-armv7-${{ github.ref_name }}
            dist/MaskLR-Go-armv7-${{ github.ref_name }}.sha256
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
